# Bài tập lập trình: Softmax Regression

```
ProtonX - TensorFlow Class
```

### Hướng dẫn làm bài
- Trong bài tập này bạn sẽ sử dụng Python 3.
- Sau khi bạn viết Code của mình xong, hãy chạy dòng Code đó để xem kết quả bên dưới.

### [Quan trọng] Chú ý
- **Không sử dụng hàm `input()` tại bất kỳ dòng lệnh nào**
- **Không thay đổi dòng code return của hàm**

Các bạn sẽ thực hiện `code` trong các phần hiển thị `#TODO: Lập trình tại đây` và thay thế các vị trí `None`. Có những câu hỏi chỉ cần trả về đáp án.

Sau khi viết xong Code của bạn, bạn hãy ấn "SHIFT"+"ENTER" để thực hiện chạy lệnh của Cell đó.

---
Điểm số:
* 10 điểm / Câu

Tiêu chí chấm điểm:
* Các bài tập sẽ được chấm dựa trên các Test-case.
* Các bạn không khởi tạo lại giá trị đầu vào bên trong hàm. Có thể khởi tạo các giá trị này ngoài hàm nhằm mục đích kiểm thử.

In [137]:
import tensorflow as tf
import numpy as np

## 1. Tải dữ liệu MNIST

In [138]:
(X_train, Y_train), (X_val, Y_val) = tf.keras.datasets.mnist.load_data()

Một số thông tin quan trọng

In [139]:
# Số lượng nhãn
num_classes = 10

num_of_train_images, width, height = X_train.shape

# Chiều ảnh được duỗi
image_vector_size = width * height


print("""
  Số lượng ảnh train: {}
  Chiều dài ảnh train: {}
  Chiều cao ảnh train: {}
  Chiều ảnh được duỗi: {}
""".format(num_of_train_images, width, height, image_vector_size))




  Số lượng ảnh train: 60000
  Chiều dài ảnh train: 28
  Chiều cao ảnh train: 28
  Chiều ảnh được duỗi: 784



## 2. Tiền xử lý dữ liệu

### 2.1. Chuyển nhãn thành vector one-hot

Dựa trên ý tưởng 1 ma trận đơn vị, ví dụ vector onehot có nhãn là 4 thì sẽ tương đương với hàng thứ 4 trong ma trận đơn vị đó, từ đó lấy được ma trận đơn vị

In [140]:
def one_hot(y, num_classes):
  """
  Đầu vào:
    y:
      Dạng: numpy array
      Miêu tả: Các giá trị nhãn
      Chiều: (batch_size,)
    num_classes:
      Dạng: Số nguyên python
      Miêu tả: Số lượng nhãn
      Điều kiện: num_classes > 0
      Ví dụ: 10
  Đầu ra:
    y_one_hot:
      Miêu tả: Trả về ma trận các vector one hot của từng nhãn
      Chiều: (batch_size, num_classes)
  """
  # Lập trình tại đây

  y_one_hot = np.squeeze(np.eye(num_classes)[y.reshape(-1)])

  return y_one_hot

In [141]:
Y_train.reshape(-1)

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

Test code

- Với nhãn 9, vector one hot của nhãn này ở vị trí chỉ mục số 9 sẽ có giá trị bằng 1., các giá trị còn lại sẽ bằng 0.
- Với nhãn 7, vector one hot của nhãn này ở vị trí chỉ mục số 7 sẽ có giá trị bằng 1., các giá trị còn lại sẽ bằng 0.

In [142]:
try:
  y_test = np.array([[9], [7]])

  y_test_one_hot = one_hot(y_test, num_classes)

  print("Vector one hot:  \n {}".format(y_test_one_hot))
  print("Chiều của vector one hot: {}".format(y_test_one_hot.shape))

  expected = np.array(
    [[0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
    [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]])

  print("Chuyển đổi one hot thành công: {}".format(np.array_equal(y_test_one_hot, expected)))

except Exception as e:
  print("Lỗi thực thi: ", e)

Vector one hot:  
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Chiều của vector one hot: (2, 10)
Chuyển đổi one hot thành công: True


**Kết quả mong đợi:**

```
Vector one hot:  
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Chiều của vector one hot: (2, 10)
Chuyển đổi one hot thành công: True
```

### 2.2. Duỗi ảnh

```TODO 1:``` Xây dựng hàm duỗi ảnh

In [143]:
Y_train.shape


(60000,)

In [144]:
def flatten_images(images):
  """
  Thực thi duỗi ảnh từ (batch_size, width, height) thành (batch_size, width x height)
  Đầu vào:
    images:
      Dạng: numpy array
      Miêu tả: Ma trận các ảnh
      Chiều: (batch_size, width, height)
      Ví dụ: (32, 28, 28)
  Đầu ra:
    flattened_images
      Miêu tả: ma trận trong đó các ảnh được duỗi thành vector
      Chiều: (batch_size, image_vector_size) = (batch_size, width x height)
      Ví dụ: (32, 28 x 28) = (32, 784)
  """
  # Lập trình tại đây

  flattened_images = images.reshape(images.shape[0], -1)

  return flattened_images

Test code

In [145]:
# TEST CODE
try:
  images = np.ones((60000, 28, 28))
  flattened_images = flatten_images(images)
  print("Chiều ảnh được duỗi: {}".format(flattened_images.shape))
except Exception as e:
   print("Lỗi thực thi: ", e)

Chiều ảnh được duỗi: (60000, 784)


**Kết quả mong đợi:**

```
Chiều ảnh được duỗi: (60000, 784)
```

```TODO 2:``` Tiến hành duỗi ảnh cả 2 tập train và validation

In [146]:
try:
  # Lập trình tại đây
  X_train = flatten_images(X_train)
  X_val = flatten_images(X_val)
except Exception as e:
  print("Lỗi thực thi: ", e)

Test code

In [147]:
# TEST CODE
try:
  print("Chiều ảnh train được duỗi: {}".format(X_train.shape))
  print("Chiều ảnh validation được duỗi: {}".format(X_val.shape))
except Exception as e:
   print("Lỗi thực thi: ", e)

Chiều ảnh train được duỗi: (60000, 784)
Chiều ảnh validation được duỗi: (10000, 784)


**Kết quả mong đợi:**

```
Chiều ảnh train được duỗi: (60000, 784)
Chiều ảnh validation được duỗi: (10000, 784)
```

### 2.3. Chuẩn hóa

```TODO 3:``` Viết hàm chuẩn hóa ảnh để các giá trị pixel nằm trong khoảng từ 0 đến 1

In [148]:
def normalize_images(images):
  """
  Hàm chuẩn hóa ảnh các giá trị pixel để nằm trong khoảng từ 0 đến 1
  Đầu vào:
    images:
      Dạng: numpy array
      Miêu tả: Ma trận các vector ảnh
      Chiều: (batch_size, image_vector_size)
      Ví dụ: (32, 784)
  Đầu ra:
    normailized_images
      Miêu tả: ma trận trong đó các vector ảnh được chuẩn hóa
      Chiều: (batch_size, image_vector_size)
      Ví dụ: (32, 784)
  """
  # Lập trình tại đây

  normailized_images = images / 255.0

  return normailized_images

```TODO 4:``` Sử dụng hàm chuẩn hóa với 2 tập dữ liệu

In [149]:
try:
  # Lập trình tại đây
  X_train = normalize_images(X_train)
  X_val = normalize_images(X_val)
except Exception as e:
   print("Lỗi thực thi: ", e)

Test code

In [150]:
# TEST CODE
try:
  is_train_good = np.array_equal((X_train >= 0).astype(int), np.ones(X_train.shape)) and \
    np.array_equal((X_train <= 1).astype(int), np.ones(X_train.shape))

  is_val_good = np.array_equal((X_val >= 0).astype(int), np.ones(X_val.shape)) and \
    np.array_equal((X_val <= 1).astype(int), np.ones(X_val.shape))

  print("Ảnh train đã được chuẩn hóa: {}".format(is_train_good))
  print("Ảnh validation đã được chuẩn hóa: {}".format(is_val_good))
except Exception as e:
   print("Lỗi thực thi: ", e)

Ảnh train đã được chuẩn hóa: True
Ảnh validation đã được chuẩn hóa: True


**Kết quả mong đợi:**

```
Ảnh train đã được chuẩn hóa: True
Ảnh validation đã được chuẩn hóa: True
```

## 3. Xây dựng mô hình

### **Quan trọng:** Nhằm đơn giản quy trình, các hàm bên dưới được thiết kế theo SGD thực hiện tính toán **trên 1 điểm dữ liệu**.

### 3.1. Thiết kết phép nhân tuyến tính Feed Forward

```TODO 5:``` Thiết kế phép nhân tuyến tính Feed Forward

- $n$: Chiều ảnh được duỗi (image_vector_size: 784)
- $c$: Số lượng nhãn (num_classes: 10) \
- Tham số: $\theta$

$$\theta \in \mathbb{R}^{n \times c}$$

- 1 ảnh đầu vào: $\textbf{x}$

$$\textbf{x} \in \mathbb{R}^{n \times 1}$$

- Đầu ra $\textbf{z}$:

$$\textbf{z} = \theta^T\textbf{x}  $$
$$\textbf{z} \in \mathbb{R}^{c \times 1} $$

In [151]:
def cal_z(theta, x):
  """
  Thực hiện nhân tuyến tính theta và x, x là 1 điểm dữ liệu
  Đầu vào:
    theta:
      Dạng: numpy array
      Miêu tả: Ma trận theta.
      Chiều: (image_vector_size, num_classes)
      Ví dụ: (784, 10)
    x:
      Dạng: numpy array
      Miêu tả: Vector ảnh x
      Chiều: (image_vector_size, 1)
      Ví dụ: (784, 1)
  Đầu ra:
    z:
      Dạng: numpy array
      Miêu tả: Vector đầu ra z
      Chiều: (num_classes, 1)
      Ví dụ: (10, 1)
  """
  # Lập trình tại đây

  z = theta.T.dot(x)
  return z

Test code

In [152]:
try:
  theta = np.random.normal(size=(784, 10))
  x = np.ones((784, 1))
  z = cal_z(theta, x)

  print("Chiều của vector z: {}".format(z.shape))

except Exception as e:
  print("Lỗi thực thi: ", e)

Chiều của vector z: (10, 1)


**Kết quả mong đợi:**

```
Chiều của vector z: (10, 1)
```

### 3.2. Thiết kế hàm Softmax

```TODO 6:``` Thiết kế hàm softmax

$$\hat{\textbf{y}} = \text{softmax}(\textbf{z}) = \text{softmax}(\begin{bmatrix}
z_1 \\
\ \vdots \\
z_c \\
\end{bmatrix}) =   \begin{bmatrix}
\frac{e^{z_1}}{\sum_{t=1}^ce^{z_t}}\\
\ \vdots \\
\frac{e^{z_c}}{\sum_{t=1}^ce^{z_t}}\\
\end{bmatrix} $$

Trường hợp này có 10 nhãn nên $c = 10$ cho nên

$$\hat{\textbf{y}}  = \text{softmax}(\textbf{z}) =   \begin{bmatrix}
\frac{e^{z_1}}{\sum_{t=1}^{10}e^{z_t}}\\
\ \vdots \\
\frac{e^{z_{10}}}{\sum_{t=1}^{10}e^{z_t}}\\
\end{bmatrix} $$



In [153]:
def softmax(z):
  """
  Thực hiện hàm softmax trên vector z
  Đầu vào:
    z:
      Dạng: numpy array
      Miêu tả: Vector z. Đầu ra của phép nhân tuyến tính
      Chiều: (num_classes, 1)
      Ví dụ: (10, 1)
  Đầu ra:
    y_hat:
      Dạng: numpy array
      Miêu tả: Chuẩn hóa vector z theo phân phối softmax có tổng các giá trị bằng 1
      Chiều: (num_classes, 1)
      Ví dụ: (10, 1)
  """
  # Lập trình tại đây

  z = np.exp(z)
  y_hat = z / np.sum(z)

  return y_hat

In [154]:
z

array([[ -1.72568066],
       [ -1.24937879],
       [-15.6149633 ],
       [ -9.02113348],
       [ 19.04184432],
       [ -2.52592607],
       [-10.13115941],
       [-52.57024301],
       [  1.40485534],
       [  7.18886341]])

Test code

In [155]:
# TEST CODE
try:
  ez = np.random.normal(size=(10, 1))
  ez = softmax(ez)
  print("Chiều của vector softmax: {}".format(ez.shape))
  print("Các giá trị của vector này được chuẩn hóa: {}".format(0.99 <= np.sum(ez) <= 1))
except Exception as e:
   print("Lỗi thực thi: ", e)

Chiều của vector softmax: (10, 1)
Các giá trị của vector này được chuẩn hóa: True


**Kết quả mong đợi:**

```
Chiều của vector softmax: (10, 1)
Các giá trị của vector này được chuẩn hóa: True
```

### 3.3. Thiết kết Softmax Regression

```TODO 7:``` Kết hợp 2 hàm
- `cal_z`
- `softmax`

để được softmax regression đầy đủ.

In [156]:
def cal_y_hat(theta, x):
  """
  Sử dụng hàm tính z và đưa z qua lớp softmax để tính đầu ra hàm softmax
  Đầu vào:
    theta:
      Dạng: numpy array
      Miêu tả: Ma trận theta.
      Chiều: (image_vector_size, num_classes)
      Ví dụ: (784, 10)
    x:
      Dạng: numpy array
      Miêu tả: Vector ảnh x
      Chiều: (image_vector_size, 1)
      Ví dụ: (784, 1)
  Đầu ra:
    y_hat:
      Dạng: numpy array
      Miêu tả: Vector đầu ra của softmax
      Chiều: (num_classes, 1)
      Ví dụ: (10, 1)
  """

  # Lập trình tại đây

  # Tính z
  z = theta.T.dot(x)

  # Tính y_hat
  exp_z = np.exp(z)
  y_hat = exp_z / np.sum(exp_z, axis=0, keepdims=True)

  return y_hat

Test code

In [157]:
try:
  theta = np.random.normal(size=(784, 10))
  x = np.ones((784, 1))
  y_hat = cal_y_hat(theta, x)

  print("Chiều của vector y_hat: {}".format(y_hat.shape))

  is_train_good = 0.99 <= np.sum(y_hat) <= 1

  print("Các giá trị đã đưa qua softmax: {}".format(is_train_good))

except Exception as e:
  print("Lỗi thực thi: ", e)

Chiều của vector y_hat: (10, 1)
Các giá trị đã đưa qua softmax: True


**Kết quả mong đợi:**

```
Chiều của vector y_hat: (10, 1)
Các giá trị đã đưa qua softmax: True
```

### 3.4. Thiết kết hàm tính giá trị mất mát trên 1 điểm dữ liệu

```TODO 8:``` Thiết kế hàm tính giá trị mất mát trên 1 điểm dữ liệu (cross entropy)

Hàm mất mát trên 1 điểm dữ liệu

$ cost(\theta, (\textbf{x}, \textbf{y})) = - \textbf{y}\log(\hat{\textbf{y}})
$

Vậy trường hợp này ta sẽ:

1. **Lấy giá trị âm** phép nhân vô hướng giữa vector one hot của nhãn với vector đầu ra của Softmax. Chú ý giá trị này là một số.

In [158]:
def cross_entropy(y_hat, y):
  """
  Hàm giá trị mất mát tại 1 điểm dữ liệu
  Đầu vào:
    y_hat:
      Dạng: numpy array
      Miêu tả: Vector đầu ra của softmax
      Chiều: (num_classes, 1)
      Ví dụ: (10, 1)
    y:
      Dạng: numpy arry
      Miêu tả: Vector one hot của nhãn
      Chiều: (num_classes, 1)
      Chiều: (10, 1)
  Đầu ra:
    loss:
      Dạng: số thực
      Miêu tả: Giá trị mất mát trên 1 điểm dữ liệu
      Ví dụ: 0.36
  """

  # Lập trình tại đây

  # Tính giá trị sai lệch
  loss = np.sum(-y * np.log(y_hat))

  return loss

Test code

In [159]:
try:
  np.random.seed(seed=42)
  theta = np.ones((784, 10))

  x = np.zeros((784, 1))

  y_hat = cal_y_hat(theta, x)

  y = np.array([[1.],[0.],[0.],[0.],[0.],[0.],[0.],[0.],[0.],[0.]])

  loss = cross_entropy(y_hat, y)

  print("Giá trị mất mát: {}".format(loss))

except Exception as e:
  print("Lỗi thực thi: ", e)

Giá trị mất mát: 2.3025850929940455


**Kết quả mong đợi:**

```
Giá trị mất mát: 2.3025850929940455
```

### 3.5. Thiết kế hàm tính gradient của mất mát 1 điểm dữ liệu trên tham số

```TODO 9:``` Thiết kế hàm tính gradient của mất mát 1 điểm dữ liệu trên tham số

Công thức tính gradient của hàm mất mát 1 điểm dữ liệu với tham số

$$
\nabla_{\theta}cost(\theta, (\textbf{x}, \textbf{y})) = \textbf{x}(h_\theta(\textbf{x}) - \textbf{y})^T = \textbf{x}(\hat{\textbf{y}} - \textbf{y})^T
$$

In [160]:
def gradient(y_hat, x, y):
  """
  Hàn tính Gradient của giá trị mất mát của 1 điểm dữ liệu với tham số theta
  Đầu vào:
    y_hat:
      Dạng: numpy array
      Miêu tả: Vector đầu ra của softmax
      Chiều: (num_classes, 1)
      Ví dụ: (10, 1)
    x:
      Dạng: numpy array
      Miêu tả: Vector ảnh x
      Chiều: (image_vector_size, 1)
      Ví dụ: (784, 1)
    y:
      Dạng: numpy array
      Miêu tả: Vector one hot của nhãn
      Chiều: (num_classes, 1)
      Ví dụ: (10, 1)
  Đầu ra:
    grad:
      Dạng: numpy array
      Miêu tả: Gradient của giá trị mất mát của 1 điểm dữ liệu với tham số theta
      Chiều: (image_vector_size, num_classes)
      Ví dụ: (784, 10)
  """
  # Lập trình tại đây

  # Áp dụng công thức tính gradient
  grad = x.dot((y_hat - y).T)

  return grad

Test code

In [161]:
try:
  np.random.seed(seed=42)
  theta = np.random.normal(size=(784, 10))

  x = np.zeros((784, 1))

  y = np.array([[1.],[0.],[0.],[0.],[0.],[0.],[0.],[0.],[0.],[0.]])

  y_hat = cal_y_hat(theta, x)

  grad = gradient(y_hat, x, y)

  print("Chiều của gradient: {}".format(grad.shape))

except Exception as e:
  print("Lỗi thực thi: ", e)

Chiều của gradient: (784, 10)


**Kết quả mong đợi:**

```
Chiều của gradient: (784, 10)
```

### 3.6. Thiết kết hàm tính độ chính xác của mô hình

```TODO 10:``` Thiết kế hàm tính độ chính xác trên toàn bộ tập dữ liệu

In [162]:
def cal_acc(theta, X, Y):
  """
  Tính độ chính xác của mô hình trên toàn bộ tập dữ liệu
    Bước 1: Thực hiện feed forward để lấy kết quả dự đoán
    Bước 2: So sánh kết quả dự đoán với nhãn thật
  Đầu vào:
    theta:
      Dạng: numpy array
      Miêu tả: Ma trận theta.
      Chiều: (image_vector_size, num_classes)
      Ví dụ: (784, 10)
    X:
      Dạng: numpy array
      Miêu tả: Các vector ảnh
      Chiều: (batch_size, image_vector_size)
      Ví dụ: (60000, 784)
    Y:
      Dạng: numpy arry
      Miêu tả: Các vector của nhãn
      Chiều: (batch_size, 1)
      Ví dụ: (60000, 1)
  Đầu ra:
    acc:
      Dạng: số thực
      Miêu tả: Độ chính xác của mô hình tại thời điểm hiện tại
      Ví dụ: 0.6
  """
  # Lập trình tại đây

  # Bước 1: Tính kết quả dự đoán trên toàn bộ tập dữ liệu, thông qua việc đưa qua hàm softmax
  # Chiều: Y_hat (batch_size, num_classes). Ví dụ (60000, 10)
  # coi Y_hat là vector dự đoán
  Y_hat = softmax(X.dot(theta)) # ở vị trí số nào thì xác suất xuất hiện số đó là lớn nhất thì lấy nên ở phía dưới sử dụng np.argmax

  # Bước 2: Tính độ chính xác mô hình

  acc =np.mean(np.argmax(Y_hat,axis = 1) == Y) # reshape(-1, 1) nhằm giữ nguyên các phần tử và duỗi vecto Y_hat ra thành 1 cột



  return acc

Test code

In [163]:
try:
  np.random.seed(seed=42)

  theta = np.random.normal(size=(784, 10))

  X = np.zeros((60000, 784))

  Y = np.random.randint(0, 10, (60000,))

  acc = cal_acc(theta, X, Y)

  print("Độ chính xác hiện tại: {}".format(acc))

except Exception as e:
  print("Lỗi thực thi: ", e)

Độ chính xác hiện tại: 0.09811666666666667


**Kết quả mong đợi:**

```
Độ chính xác hiện tại: 0.09811666666666667

```

## 4. Tiến hành training

In [164]:
from sklearn.utils import shuffle

### 4.1. Khởi tạo tham số theta

In [165]:
np.random.seed(seed=42)

theta = np.random.normal(size=(image_vector_size, num_classes))

### 4.2. Thiết kế hàm SGD

```TODO 11:``` Thiết kế hàm SGD

Qúa trình training:

- Chạy vòng lặp, ở mỗi vòng lặp (epoch)
  - Xáo (Shuffle) ngẫu nhiên bộ dữ liệu
  - Lặp i từ 1 đến m
  - Cập nhật theta với công thức
  $$
\theta := \theta - \nabla_{\theta}cost(\theta, (\textbf{x}, \textbf{y}))
 $$

Giá trị  $\nabla_{\theta}cost(\theta, (\textbf{x}, \textbf{y}))$ đã được tính bởi hàm `cross_entropy`




In [166]:
def SGD(X_train, Y_train, X_val, Y_val, theta, learning_rate, epochs):

  """
  Hàm training sử dụng SGD
  Đầu vào:
    X_train:
      Dạng: numpy array
      Miêu tả: Các vector ảnh bộ train
      Chiều: (batch_size, image_vector_size)
      Ví dụ: (60000, 784)
    Y_train:
      Dạng: numpy arry
      Miêu tả: Vector nhãn bộ train
      Chiều: (batch_size, 1)
      Ví dụ: (60000,)
    X_val:
      Dạng: numpy array
      Miêu tả: Các vector ảnh bộ validation
      Chiều: (batch_size, image_vector_size)
      Ví dụ: (10000, 784)
    Y_val:
      Dạng: numpy arry
      Miêu tả: Vector nhãn bộ validation
      Chiều: (batch_size, 1)
      Ví dụ: (10000,)
    theta:
      Dạng: numpy array
      Miêu tả: Ma trận theta.
      Chiều: (image_vector_size, num_classes)
      Ví dụ: (784, 10)
    learning_rate:
      Dạng: số thực
      Miêu tả: Tốc độ học
      Ví dụ: 0.0001
    epochs:
      Dạng: số nguyên dương
      Miêu tả: Số vòng lặp qua bộ dữ liệu
      Ví dụ: 20
  Đầu ra:
    Tuple: (theta, acc, val_acc) với
      theta:
        Dạng: numpy array
        Miêu tả: Ma trận theta đã được học
        Chiều: (image_vector_size, num_classes)
        Ví dụ: (784, 10)
      acc:
        Dạng: số thực
        Miêu tả: Độ chính xác của mô hình trên tập train
        Ví dụ: 0.6
      val_acc:
        Dạng: số thực
        Miêu tả: Độ chính xác của mô hình trên tập validation
        Ví dụ: 0.1
  """
  # Số điểm dữ liệu
  m = len(X_train)

  for j in range(epochs):

    # Bước 1: Tráo bộ dữ liệu train
    X_train, Y_train = shuffle(X_train, Y_train)

    # Định nghĩa giá trị mất mát trên toàn bộ epoch
    cost = 0

    # Bước 2: Lặp qua từng điểm dữ liệu tập train
    for i in range(m):

      # Bước 2.1: Lấy x và y ở vị trí i
      # chiều x: (784, 1)

      x = X_train[i].reshape(-1,1)

      # chiều y: (1, 1)
      y = Y_train[i]

      # Bước 2.2: Chuyển nhãn y thành vector one-hot
      y = one_hot(y, num_classes).reshape(-1,1)

      # Bước 2.3: Tính đầu ra của Softmax Regression với điểm dữ liệu này
      y_hat = softmax(cal_z(theta, x))

      # Bước 2.4: Tính giá trị mất mát trên điểm dữ liệu này
      loss = cross_entropy(y_hat, y)

      # Bước 2.5: Bổ sung giá trị loss vào giá trị cost

      cost += loss

      # Bước 2.6: Cập nhật theta thông qua learning_rate và gradient
      theta = theta - learning_rate * gradient(y_hat, x, y)

    # Bước 3: Tính độ chính xác
    # Bước 3.1: Tính độ chính xác trên tập train
    print
    acc = cal_acc(theta, X_train, Y_train)

    # Bước 3.2: Tính độ chính xác trên tập validation

    val_acc = cal_acc(theta, X_val, Y_val)

    print("Epoch: {}, loss: {:.3f}, acc: {:.3f}, val_acc: {:.3f}".format(j + 1, cost / m, acc, val_acc))

  return theta, acc, val_acc

Testcode

In [167]:
try:
  np.random.seed(seed=42)

  theta_mock = np.random.normal(size=(784, 10))

  X_mock_train = np.ones((60000, 784))

  Y_mock_train = np.ones((60000, )).astype(int)

  X_mock_validation = np.ones((10000, 784))

  Y_mock_validation = np.ones((10000,)).astype(int)

  learning_rate_mock = 0.0001

  epochs_mock = 1

  theta_mock, acc_mock, val_acc_mock = SGD(X_mock_train, Y_mock_train, X_mock_validation, Y_mock_validation, theta_mock, learning_rate_mock, epochs_mock)

  print('Chiều của theta: {}'.format(theta_mock.shape))
  print('Giá trị chính xác trên tập train: {}'.format(acc_mock))
  print('Giá trị chính xác trên tập validation: {}'.format(val_acc_mock))

except Exception as e:
  print("Lỗi thực thi: ", e)

Epoch: 1, loss: 0.068, acc: 1.000, val_acc: 1.000
Chiều của theta: (784, 10)
Giá trị chính xác trên tập train: 1.0
Giá trị chính xác trên tập validation: 1.0


**Kết quả mong đợi:**

```
Epoch: 1, loss: 0.068, acc: 1.000, val_acc: 1.000
Chiều của theta: (784, 10)
Giá trị chính xác trên tập train: 1.0
Giá trị chính xác trên tập validation: 1.0
```

### 4.3. Tiến hành training

Kiểm tra lại chiều trước khi train

In [168]:
X_train.shape, Y_train.shape, X_val.shape, Y_val.shape

((60000, 784), (60000,), (10000, 784), (10000,))

In [169]:
try:
  learning_rate = 0.0001
  epochs = 30
  SGD(X_train, Y_train, X_val, Y_val, theta, learning_rate, epochs)

except Exception as e:
  print("Lỗi thực thi: ", e)

Epoch: 1, loss: 9.530, acc: 0.223, val_acc: 0.232
Epoch: 2, loss: 4.947, acc: 0.398, val_acc: 0.413
Epoch: 3, loss: 3.179, acc: 0.524, val_acc: 0.550
Epoch: 4, loss: 2.416, acc: 0.599, val_acc: 0.621
Epoch: 5, loss: 2.018, acc: 0.643, val_acc: 0.665
Epoch: 6, loss: 1.773, acc: 0.676, val_acc: 0.694
Epoch: 7, loss: 1.606, acc: 0.700, val_acc: 0.719
Epoch: 8, loss: 1.483, acc: 0.718, val_acc: 0.738
Epoch: 9, loss: 1.389, acc: 0.733, val_acc: 0.752
Epoch: 10, loss: 1.313, acc: 0.746, val_acc: 0.763
Epoch: 11, loss: 1.251, acc: 0.755, val_acc: 0.772
Epoch: 12, loss: 1.199, acc: 0.764, val_acc: 0.781
Epoch: 13, loss: 1.154, acc: 0.771, val_acc: 0.787
Epoch: 14, loss: 1.114, acc: 0.778, val_acc: 0.795
Epoch: 15, loss: 1.080, acc: 0.783, val_acc: 0.799
Epoch: 16, loss: 1.049, acc: 0.788, val_acc: 0.804
Epoch: 17, loss: 1.021, acc: 0.793, val_acc: 0.809
Epoch: 18, loss: 0.996, acc: 0.797, val_acc: 0.812
Epoch: 19, loss: 0.973, acc: 0.800, val_acc: 0.815
Epoch: 20, loss: 0.952, acc: 0.804, val_

**Kết quả mong đợi (Tương đối):**

```
Epoch: 1, loss: 9.530, acc: 0.223, val_acc: 0.232
Epoch: 2, loss: 4.947, acc: 0.398, val_acc: 0.413
Epoch: 3, loss: 3.179, acc: 0.524, val_acc: 0.550
Epoch: 4, loss: 2.416, acc: 0.599, val_acc: 0.621
Epoch: 5, loss: 2.018, acc: 0.643, val_acc: 0.665
Epoch: 6, loss: 1.773, acc: 0.676, val_acc: 0.694
Epoch: 7, loss: 1.606, acc: 0.700, val_acc: 0.719
Epoch: 8, loss: 1.483, acc: 0.718, val_acc: 0.738
Epoch: 9, loss: 1.389, acc: 0.733, val_acc: 0.752
Epoch: 10, loss: 1.313, acc: 0.746, val_acc: 0.763
Epoch: 11, loss: 1.251, acc: 0.755, val_acc: 0.772
Epoch: 12, loss: 1.199, acc: 0.764, val_acc: 0.781
Epoch: 13, loss: 1.154, acc: 0.771, val_acc: 0.787
Epoch: 14, loss: 1.114, acc: 0.778, val_acc: 0.795
Epoch: 15, loss: 1.080, acc: 0.783, val_acc: 0.799
Epoch: 16, loss: 1.049, acc: 0.788, val_acc: 0.804
Epoch: 17, loss: 1.021, acc: 0.793, val_acc: 0.809
Epoch: 18, loss: 0.996, acc: 0.797, val_acc: 0.812
Epoch: 19, loss: 0.973, acc: 0.800, val_acc: 0.815
Epoch: 20, loss: 0.952, acc: 0.804, val_acc: 0.819
Epoch: 21, loss: 0.932, acc: 0.807, val_acc: 0.823
Epoch: 22, loss: 0.914, acc: 0.811, val_acc: 0.827
Epoch: 23, loss: 0.898, acc: 0.813, val_acc: 0.828
Epoch: 24, loss: 0.882, acc: 0.816, val_acc: 0.831
Epoch: 25, loss: 0.868, acc: 0.818, val_acc: 0.833
Epoch: 26, loss: 0.854, acc: 0.820, val_acc: 0.835
Epoch: 27, loss: 0.841, acc: 0.823, val_acc: 0.838
Epoch: 28, loss: 0.829, acc: 0.825, val_acc: 0.840
Epoch: 29, loss: 0.817, acc: 0.827, val_acc: 0.842
Epoch: 30, loss: 0.806, acc: 0.829, val_acc: 0.844
```

### Vậy là bạn đã xây dựng thành công một mô hình phân loại nhiều biến bằng numpy thuần rồi đó ;)

<img src="https://storage.googleapis.com/protonx-cloud-storage/icons/1108-ferris-wheel-outline.gif" width=300 />